# Generated by Django 4.2.9 on 2024-01-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Addimage',
            new_name='addimage',
        ),
    ]
