# Generated by Django 4.2.9 on 2024-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_coupons_is_active_coupons_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
