# Generated by Django 4.2.9 on 2024-02-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_coupons_valid_from_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
