# Generated by Django 4.2.6 on 2024-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002B6DB737CE0>', max_length=200),
        ),
    ]
