# Generated by Django 4.2.6 on 2024-01-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000299F2307CE0>', max_length=200),
        ),
    ]
