# Generated by Django 4.2.9 on 2024-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_profile_pic_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.FileField(blank=True, default='', upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001B0B0DCF9C0>', max_length=200),
        ),
    ]
