# Generated by Django 4.2.9 on 2024-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_account_profile_pic_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000025E155BBEC0>', max_length=200),
        ),
    ]
