# Generated by Django 4.2.9 on 2024-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000248AD02BBA0>', max_length=200),
        ),
    ]
