# Generated by Django 4.2.9 on 2024-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_account_wallet_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='on_del',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001DB3E93BBA0>', max_length=200),
        ),
    ]
