# Generated by Django 4.2.9 on 2024-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_is_available',
            field=models.BooleanField(default=True),
        ),
    ]
