# Generated by Django 4.2.9 on 2024-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Return Received', 'Return Received'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Payment Pending', 'Payment Pending')], default='Pending', max_length=100),
        ),
    ]
